
namespace LogoIcon
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    static class IconFont
    {
        public const string LogoFill = "\ue900";
        public const string Logo = "\ue901";
    }
}